### ISSUE TITLE
Placement of Example Notebooks

### ISSUE THREAD

**Issue by jzf2101** [datamicroscopes/kernels#4]
I think these should be moved to a different folder/repo.  Not sure why they would be in kernels instead of release.

**Comment by jzf2101** [comment]
@ericmjonas do you have an opinion on this?

**Comment by ericmjonas** [comment]
My understanding was there wasn't a lot of code that was supposed to live
in release, it was just supposed to be a build-aggregator.

**Comment by jzf2101** [comment]
My thinking was release has our documentation - it may be useful to include examples in our documentation the same way a lot of libraries do
